### PR TITLE
Fix calling out to elastix command

### LINKED ISSUE #1: No such file or directory:'/tmp/pyelastix/../result.0.mhd'
Hi,

I get the following error:

```
In [26]:im3, field = pyelastix.register(im1, im2, params)
Calling Elastix to register images ...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-27-67b09ffdefda> in <module>()
----> 1 im3, field = pyelastix.register(im1, im2, params)

/usr/local/lib/python2.7/dist-packages/pyelastix.pyc in register(im1, im2, params, exact_params, verbose)
    507         except IOError as why:
    508             tmp = "An error occured during registration: " + str(why)
--> 509             raise RuntimeError(tmp)
    510
    511     # Find deformation field

RuntimeError: An error occured during registration: [Errno 2] No such file or directory: '/tmp/pyelastix/id_3862_140449827452240/result.0.mhd'
```

In that folder there is no result.0mhd file but there are im1.mhd,  im1.raw,  im2.mhd,  im2.raw, and  params.txt.

Have you ever see such an error or do you know how to solve it?

Thanks

Edit: 1. Environment is Ubuntu 14.04 and 16.04  and 2. Elastix works properly from command line :
elastix -f im1.png -m im2.png -out /tmp/pyelastix/xx -p /tmp/pyelastix/xx/params.txt

### PR DESCRIPTION
**Pull request by cancan101**
Closes https://github.com/almarklein/pyelastix/issues/1

### CODE REVIEW

**Comment by soupault** [comment]
Thank you for the PR! This fix is now a part of #20 and it will be shipped with the new release.

**Comment by bamford** [comment]
Why hasn't this small but essential fix been merged into the main branch and released? Or alternatively @soupault's branch been released as the official version? If pyelastix is installed from pip or conda it is currently broken!

**Comment by almarklein** [comment]
@bamford thanks for the heads-up. Maintaining an open source package can be a burden, and lack of time is always a problem. As for me, my interests have shifted to other areas, so I would be happy if others take over maintenance of this package.

As for now, #20 has now been merged. We can do a release, or is there anything else you'd like to do first @soupault ?

**Comment by soupault** [comment]
@almarklein I think it would be fine to make a release as-is. I don't have any big plans on changing the API, currently. Several major bugs have been fixed, so many people should benefit from that.

**Comment by almarklein** [comment]
Ok, I'll push to Pypi

**Comment by almarklein** [comment]
done!

**Comment by bamford** [comment]
Thank you for your very quick response! Sorry if my comment yesterday came across a bit blunt. I completely appreciate the problem: the more useful things you produce, the more you are expected to look after! Many thanks to both of you for putting together and maintaining this software.

**Pull request closed without merging**
